# Example dictionary mapping keys to a list of commands
commands = {0: [],
 1: ['OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=1 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs250_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=1 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs1500_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=1 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs2750_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=1 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs4000_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle'],
 2: [],
 3: ['OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=3 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs500_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=3 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs1750_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=3 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs3000_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=3 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs4250_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle'],
 4: [],
 5: ['OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=5 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs750_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=5 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs2000_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=5 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs3250_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=5 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs4500_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle'],
 6: ['OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=6 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs1000_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=6 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs2250_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=6 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs3500_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=6 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs4750_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle'],
 7: ['OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=7 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs1250_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=7 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs2500_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle',
  'OMP_NUM_THREADS=64 CUDA_VISIBLE_DEVICES=7 mpirun --allow-run-as-root --bind-to none --oversubscribe -np 1 python src/main.py                 --config config/meta_test/image-mlp-fmst_fedlagg-adafac.py,config/learned_optimizer/muadafacmlploptbc.py                 --task mutransformer-w1024-d3_lm1b-s64-v32k                 --optimizer MuAdafacMLPLOptBC                 --name_suffix gs3750_OPH-A_w0.1_std01_bs128                 --wandb_checkpoint_id <NEED>/mup-meta-training/zrv6wgj1                 --local_batch_size 128                 --test_project mup-meta-testing                 --num_runs 2                 --num_inner_steps 5000                 --needs_state                 --gradient_accumulation_steps 1                 --adafac_step_mult 0.01                 --test_interval 100                 --selected_checkpoint global_step5000/optimizer_ckpt.pickle']}
import os
import argparse

# Parse command line arguments
parser = argparse.ArgumentParser(description='Generate shell scripts for running commands.')
parser.add_argument('--exec_dir', type=str, default='.', help='Directory from which to execute the commands')
args = parser.parse_args()


# Directory to save the .sh files
output_dir = 'generated_scripts'
os.makedirs(output_dir, exist_ok=True)

# Prefix to include in each script
prefix = '#!/bin/bash\n# Auto-generated script\n'

for key, cmd_list in commands.items():
    script_content = f"{prefix}# Key: {key}\n"
    script_content += f"cd {args.exec_dir}\n\n"
    script_content += '\n'.join(cmd_list) + '\n'
    script_path = os.path.join(output_dir, f"{key}.sh")
    with open(script_path, 'w') as f:
        f.write(script_content)
    # Make the script executable
    os.chmod(script_path, 0o755)

print(f"Generated {len(commands)} scripts in '{output_dir}' directory.") 